# spring.application.name=springboot

# server.port = 9090

# spring.datasource.driver-class-name=com.mysql.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/stev
# spring.datasource.username=root
# spring.datasource.password=123456

# 服务器地址
server:
  port: 9090

# sql数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stev
    username: root
    password: steven123

# mybatis mapper: 配置resources/mapper里的xml
mybatis:
  mapper-locations: 
    classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl